### PR TITLE
bump shader version to 150

### PR DESCRIPTION
**Pull request by Godlander**
version 120 is a bit outdated and doesn't work for macs

i'm not certain if i updated everything properly, but it works ingame
tested on 1.17 for windows and mac

### CODE REVIEW

**Comment by bradleyq** [comment]
Master branch technically does not support 1.17 (its just that most of the shader works). This is resolved in 1.17 / 1.18 dev branch. Also, I recall not upgrading to 150 since this shader is made for 1.16 and gl_NormalMatrix is removed and it is **required** for dynamic FOV to work correctly. Did you confirm ModelViewMat is populated in 1.16 (and not simply I)?

**Comment by Godlander** [comment]
i didnt confirm
what sort of bugs would that cause?
i didn't notice any visual errors when changing FOV manually or by sprinting/effects.

**Comment by bradleyq** [comment]
biggest indicator would be slanted / distorted screen space reflections at certain angles when FOV is not 70.

**Comment by Godlander** [comment]
ah yeah i do notice it. it's especially apparant when looking at sugarcanes from the edge of screen

the problem i have with dev branch is that it deviates way too far from the vanilla aesthetic. would it be possible to have a version without the custom lighting and sky?

i tried to play with the code but i'm not experienced enough to make sense of it.

**Comment by bradleyq** [comment]
well it is actively in dev. Missing features: HDR, subsurface scattering, bloom, autoexposure, ss shadows. These will probably make any issues you see now go away.

about the grass. This will be fixed in subsurface.

about the sky. I also dislike it but I haven't found a solution yet. tbf I didn't spend much time on it yet since I have other priorities first.

When I am done I _might_ make a lite version, but it is unlikely. you will either need to live with the problems of the 1.16 version or try to modify it to suit your own needs. ATM I don't want to break 1.16 compatibility on master branch.

**Comment by Godlander** [comment]
got it. ill wait for dev branch and see

**Pull request closed without merging**
